name: Build APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Rubberduckycooly/RSDKv5-Decompilation
          path: RSDKv5
      - name: Checkout Data
        uses: actions/checkout@v4
        with:
          repository: Rubberduckycooly/Sonic-Mania-Decompilation
          path: Sonic-Mania
      - name: Build APK
        run: |
          cd RSDKv5
          mkdir build && cd build
          cmake .. -DRETRO_DISABLE_PLUS=off -DRETRO_REVISION=3
          make
